"""forecasts and reports

Revision ID: 3353efdb6378
Revises: c782c41ba983
Create Date: 2026-07-18 23:01:01.330741
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3353efdb6378'
down_revision: str | None = 'c782c41ba983'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('metric_column', sa.String(length=120), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('horizon', sa.SmallInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=40), nullable=False),
    sa.Column('backtest_mape', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecasts_project_id'), ['project_id'], unique=False)

    op.create_table('reports',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_project_id'))

    op.drop_table('reports')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecasts_project_id'))

    op.drop_table('forecasts')
    # ### end Alembic commands ###
