"""cleaning_logs

Revision ID: e47ae3daf09b
Revises: 687fe49665e0
Create Date: 2026-07-18 14:25:53.479583
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e47ae3daf09b'
down_revision: str | None = '687fe49665e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning_logs',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('rule_name', sa.String(length=50), nullable=False),
    sa.Column('column_name', sa.String(length=120), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('rows_affected', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cleaning_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cleaning_logs_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleaning_logs_project_id'))

    op.drop_table('cleaning_logs')
    # ### end Alembic commands ###
